name: MiniGame
version: '1.0-SNAPSHOT'
main: me.weirdestboi.minigame.MiniGame
api-version: 1.18
commands:
  game:
    description: The Main Command for this MiniGame-Plugin!
  sb:
    description: test