name: MiniGame
version: '${project.version}'
main: me.weirdestboi.minigame.MiniGame
api-version: 1.18
commands:
  game:
    description: The Main Command for this MiniGame-Plugin!
  sb:
    description: test